		dc.l Obj_Ring				; 0
		dc.l Obj_Monitor			; 1
		dc.l Obj_PathSwap			; 2
		dc.l Obj_MHZTwistedVine			; 3
		dc.l Obj_CollapsingPlatform		; 4
		dc.l Obj_AIZLRZEMZRock			; 5
		dc.l Obj_MHZPulleyLift			; 6
		dc.l Obj_Spring				; 7
		dc.l Obj_Spikes				; 8
		dc.l Obj_MHZCurledVine			; 9
		dc.l Obj_MHZStickyVine			; $A
		dc.l Obj_MHZSwingBarHorizontal		; $B
		dc.l Obj_MHZSwingBarVertical		; $C
		dc.l Obj_BreakableWall			; $D
		dc.l Obj_TwistedRamp			; $E
		dc.l Obj_CollapsingBridge		; $F
		dc.l Obj_MHZSwingVine			; $10
		dc.l Obj_MHZMushroomPlatform		; $11
		dc.l Obj_MHZMushroomParachute		; $12
		dc.l Obj_MHZMushroomCatapult		; $13
		dc.l Obj_Updraft			; $14
		dc.l Obj_LRZCorkscrew			; $15
		dc.l Obj_LRZWallRide			; $16
		dc.l Obj_LRZSinkingRock			; $17
		dc.l Obj_LRZFallingSpike		; $18
		dc.l Obj_LRZDoor			; $19
		dc.l Obj_LRZBigDoor			; $1A
		dc.l Obj_LRZFireballLauncher		; $1B
		dc.l Obj_LRZButtonHorizontal		; $1C
		dc.l Obj_LRZShootingTrigger		; $1D
		dc.l Obj_LRZDashElevator		; $1E
		dc.l Obj_LRZLavaFall			; $1F
		dc.l Obj_LRZSwingingSpikeBall		; $20
		dc.l Obj_LRZSmashingSpikePlatform	; $21
		dc.l Obj_LRZSpikeBall			; $22
		dc.l Obj_MHZMushroomCap			; $23
		dc.l Obj_AutomaticTunnel		; $24
		dc.l Obj_LRZChainedPlatforms		; $25
		dc.l Obj_AutoSpin			; $26
		dc.l Obj_S2LavaMarker			; $27
		dc.l Obj_InvisibleBlock			; $28
		dc.l Obj_LRZFlameThrower		; $29
		dc.l Obj_CorkFloor			; $2A
		dc.l Obj_LRZOrbitingSpikeBallHorizontal	; $2B
		dc.l Obj_LRZOrbitingSpikeBallVertical	; $2C
		dc.l Obj_LRZSolidMovingPlatforms	; $2D
		dc.l Obj_LRZSolidRock			; $2E
		dc.l Obj_StillSprite			; $2F
		dc.l Obj_AnimatedStillSprite		; $30
		dc.l Obj_LRZCollapsingBridge		; $31
		dc.l Obj_LRZTurbineSprites		; $32
		dc.l Obj_Button				; $33
		dc.l Obj_StarPost			; $34
		dc.l Obj_AIZForegroundPlant		; $35
		dc.l Obj_HCZBreakableBar		; $36
		dc.l Obj_LRZSpikeBallLauncher		; $37
		dc.l Obj_SOZQuicksand			; $38
		dc.l Obj_SOZSpawningSandBlocks		; $39
		dc.l Obj_SOZPathSwap			; $3A
		dc.l Obj_SOZLoopFallthrough		; $3B
		dc.l Obj_Door				; $3C
		dc.l Obj_RetractingSpring		; $3D
		dc.l Obj_SOZPushableRock		; $3E
		dc.l Obj_SOZSpringVine			; $3F
		dc.l Obj_SOZRisingSandWall		; $40
		dc.l Obj_SOZLightSwitch			; $41
		dc.l Obj_SOZFloatingPillar		; $42
		dc.l Obj_SOZSwingingPlatform		; $43
		dc.l Obj_SOZBreakableSandRock		; $44
		dc.l Obj_SOZPushSwitch			; $45
		dc.l Obj_SOZDoor			; $46
		dc.l Obj_SOZSandCork			; $47
		dc.l Obj_SOZRapelWire			; $48
		dc.l Obj_SOZSolidSprites		; $49
		dc.l Obj_DEZFloatingPlatform		; $4A
		dc.l Obj_DEZTiltingBridge		; $4B
		dc.l Obj_DEZHangCarrier			; $4C
		dc.l Obj_DEZTorpedoLauncher		; $4D
		dc.l Obj_DEZLiftPad			; $4E
		dc.l Obj_DEZStaircase			; $4F
		dc.l Obj_DEZConveyorBelt		; $50
		dc.l Obj_FloatingPlatform		; $51
		dc.l Obj_DEZLightning			; $52
		dc.l Obj_DEZConveyorPad			; $53
		dc.l Obj_Bubbler			; $54
		dc.l Obj_DEZEnergyBridge		; $55
		dc.l Obj_DEZEnergyBridgeCurved		; $56
		dc.l Obj_DEZTunnelLauncher		; $57
		dc.l Obj_DEZGravitySwitch		; $58
		dc.l Obj_DEZTeleporter			; $59
		dc.l Obj_DEZGravityTube			; $5A
		dc.l Obj_DEZGravitySwap			; $5B
		dc.l Obj_DEZGravityHub			; $5C
		dc.l Obj_DEZRetractingSpring		; $5D
		dc.l Obj_DEZHoverMachine		; $5E
		dc.l Obj_DEZGravityRoom			; $5F
		dc.l Obj_DEZBumperWall			; $60
		dc.l Obj_DEZGravityPuzzle		; $61
		dc.l Obj_Ring				; $62
		dc.l Obj_Ring				; $63
		dc.l Obj_Ring				; $64
		dc.l Obj_Ring				; $65
		dc.l Obj_Ring				; $66
		dc.l Obj_Ring				; $67
		dc.l Obj_Ring				; $68
		dc.l Obj_Ring				; $69
		dc.l Obj_InvisibleHurtBlockHorizontal	; $6A
		dc.l Obj_InvisibleHurtBlockVertical	; $6B
		dc.l Obj_TensionBridge			; $6C
		dc.l Obj_InvisibleShockBlock		; $6D
		dc.l Obj_InvisibleLavaBlock		; $6E
		dc.l Obj_Ring				; $6F
		dc.l Obj_Ring				; $70
		dc.l Obj_Ring				; $71
		dc.l Obj_Ring				; $72
		dc.l Obj_Ring				; $73
		dc.l Obj_SSZRetractingSpring		; $74
		dc.l Obj_SSZSwingingCarrier		; $75
		dc.l Obj_SSZRotatingPlatform		; $76
		dc.l Obj_SSZCutsceneBridge		; $77
		dc.l Obj_FBZDEZPlayerLauncher		; $78
		dc.l Obj_SSZHPZTeleporter		; $79
		dc.l Obj_SSZElevatorBar			; $7A
		dc.l Obj_SSZCollapsingBridgeDiagonal	; $7B
		dc.l Obj_SSZCollapsingBridge		; $7C
		dc.l Obj_SSZBouncyCloud			; $7D
		dc.l Obj_SSZCollapsingColumn		; $7E
		dc.l Obj_SSZFloatingPlatform		; $7F
		dc.l Obj_HiddenMonitor			; $80
		dc.l Obj_EggCapsule			; $81
		dc.l Obj_CutsceneKnuckles		; $82
		dc.l Obj_CutsceneButton			; $83
		dc.l Obj_AIZPlaneIntro			; $84
		dc.l Obj_SSEntryRing			; $85
		dc.l Obj_GumballMachine			; $86
		dc.l Obj_GumballTriangleBumper		; $87
		dc.l Obj_CNZWaterLevelCorkFloor		; $88
		dc.l Obj_CNZWaterLevelButton		; $89
		dc.l Obj_FBZExitHall			; $8A
		dc.l Obj_SpriteMask			; $8B
		dc.l Obj_Madmole			; $8C
		dc.l Obj_Mushmeanie			; $8D
		dc.l Obj_Dragonfly			; $8E
		dc.l Obj_Butterdroid			; $8F
		dc.l Obj_Cluckoid			; $90
		dc.l Obj_MHZMinibossTree		; $91
		dc.l Obj_MHZMiniboss			; $92
		dc.l Obj_MHZEndBoss			; $93
		dc.l Obj_Skorp				; $94
		dc.l Obj_Sandworm			; $95
		dc.l Obj_Rockn				; $96
		dc.l Obj_SOZMiniboss			; $97
		dc.l Obj_SOZEndBoss			; $98
		dc.l Obj_Fireworm			; $99
		dc.l Obj_Iwamodoki			; $9A
		dc.l Obj_Toxomister			; $9B
		dc.l Obj_LRZRockCrusher			; $9C
		dc.l Obj_LRZMiniboss			; $9D
		dc.l Obj_LRZ3Autoscroll			; $9E
		dc.l Obj_Ring				; $9F
		dc.l Obj_EggRobo			; $A0
		dc.l Obj_SSZGHZBoss			; $A1
		dc.l Obj_SSZMTZBoss			; $A2
		dc.l Obj_SSZEndBoss			; $A3
		dc.l Obj_Spikebonker			; $A4
		dc.l Obj_Chainspike			; $A5
		dc.l Obj_DEZMiniboss			; $A6
		dc.l Obj_DEZEndBoss			; $A7
		dc.l Obj_MHZ1CutsceneKnuckles		; $A8
		dc.l Obj_MHZ1CutsceneButton		; $A9
		dc.l Hyudoro				; $AA
		dc.l set_SOZ_capsule_Hyudoro_cg		; $AB
		dc.l SOZ_capsule			; $AC
		dc.l Obj_LRZ3Platform			; $AD
		dc.l Obj_LRZ2CutsceneKnuckles		; $AE
		dc.l Obj_SSZCutsceneButton		; $AF
		dc.l Obj_HPZMasterEmerald		; $B0
		dc.l Obj_HPZPaletteControl		; $B1
		dc.l Obj_KnuxFinalBossCrane		; $B2
		dc.l Obj_StartNewLevel			; $B3
		dc.l Obj_HPZSuperEmerald		; $B4
		dc.l Obj_HPZSSEntryControl		; $B5
		dc.l Obj_DDZEndBoss			; $B6
		dc.l Obj_DDZAsteroid			; $B7
		dc.l Obj_DDZMissile			; $B8