		dc.l Obj_Ring				; 0
		dc.l Obj_Monitor			; 1
		dc.l Obj_PathSwap			; 2
		dc.l Obj_AIZHollowTree			; 3
		dc.l Obj_CollapsingPlatform		; 4
		dc.l Obj_AIZLRZEMZRock			; 5
		dc.l Obj_AIZRideVine			; 6
		dc.l Obj_Spring				; 7
		dc.l Obj_Spikes				; 8
		dc.l Obj_AIZ1Tree			; 9
		dc.l Obj_AIZ1ZiplinePeg			; $A
		dc.l Obj_SphereTest			; $B
		dc.l Obj_AIZGiantRideVine		; $C
		dc.l Obj_BreakableWall			; $D
		dc.l Obj_TwistedRamp			; $E
		dc.l Obj_CollapsingBridge		; $F
		dc.l Obj_LBZTubeElevator		; $10
		dc.l Obj_LBZMovingPlatform		; $11
		dc.l Obj_LBZUnusedElevator		; $12
		dc.l Obj_LBZExplodingTrigger		; $13
		dc.l Obj_LBZTriggerBridge		; $14
		dc.l Obj_LBZPlayerLauncher		; $15
		dc.l Obj_LBZFlameThrower		; $16
		dc.l Obj_LBZRideGrapple			; $17
		dc.l Obj_LBZCupElevator			; $28
		dc.l Obj_LBZCupElevatorPole		; $19
		dc.l Obj_LBZUnusedTiltingBridge		; $1A
		dc.l Obj_LBZPipePlug			; $1B
		dc.l Obj_LBZUnusedSolidHurt		; $1C
		dc.l Obj_LBZUnusedBarPlatform		; $1D
		dc.l Obj_LBZSpinLauncher		; $1E
		dc.l Obj_LBZLoweringGrapple		; $1F
		dc.l Obj_MGZLBZSmashingPillar		; $20
		dc.l Obj_LBZGateLaser			; $21
		dc.l Obj_LBZAlarm			; $22
		dc.l Obj_LBZUnusedForceFall		; $23
		dc.l Obj_AutomaticTunnel		; $24
		dc.l Obj_Ring				; $25
		dc.l Obj_AutoSpin			; $26
		dc.l Obj_S2LavaMarker			; $27
		dc.l Obj_InvisibleBlock			; $28
		dc.l Obj_AIZDisappearingFloor		; $29
		dc.l Obj_CorkFloor			; $2A
		dc.l Obj_AIZFlippingBridge		; $2B
		dc.l Obj_AIZCollapsingLogBridge		; $2C
		dc.l Obj_AIZFallingLog			; $2D
		dc.l Obj_AIZSpikedLog			; $2E
		dc.l Obj_StillSprite			; $2F
		dc.l Obj_AnimatedStillSprite		; $30
		dc.l Obj_LBZRollingDrum			; $31
		dc.l Obj_AIZDrawBridge			; $32
		dc.l Obj_Button				; $33
		dc.l Obj_StarPost			; $34
		dc.l Obj_AIZForegroundPlant		; $35
		dc.l Obj_HCZBreakableBar		; $36
		dc.l Obj_HCZWaterRush			; $37
		dc.l Obj_HCZCGZFan			; $38
		dc.l Obj_HCZLargeFan			; $39
		dc.l Obj_HCZHandLauncher		; $3A
		dc.l Obj_HCZWaterWall			; $3B
		dc.l Obj_Door				; $3C
		dc.l Obj_RetractingSpring		; $3D
		dc.l Obj_HCZConveyorBelt		; $3E
		dc.l Obj_HCZConveryorSpike		; $3F
		dc.l Obj_HCZBlock			; $40
		dc.l Obj_CNZBalloon			; $41
		dc.l Obj_CNZCannon			; $42
		dc.l Obj_CNZRisingPlatform		; $43
		dc.l Obj_CNZTrapDoor			; $44
		dc.l Obj_CNZLightBulb			; $45
		dc.l Obj_CNZHoverFan			; $46
		dc.l Obj_CNZCylinder			; $47
		dc.l Obj_CNZVacuumTube			; $48
		dc.l Obj_CNZGiantWheel			; $49
		dc.l Obj_Bumper				; $4A
		dc.l Obj_CNZTriangleBumpers		; $4B
		dc.l Obj_CNZSpiralTube			; $4C
		dc.l Obj_CNZBarberPoleSprite		; $4D
		dc.l Obj_CNZWireCage			; $4E
		dc.l Obj_SinkingMud			; $4F
		dc.l Obj_MGZTwistingLoop		; $50
		dc.l Obj_FloatingPlatform		; $51
		dc.l Obj_MGZLBZSmashingPillar		; $52
		dc.l Obj_MGZSwingingPlatform		; $53
		dc.l Obj_Bubbler			; $54
		dc.l Obj_MGZHeadTrigger			; $55
		dc.l Obj_MGZMovingSpikePlatform		; $56
		dc.l Obj_MGZTriggerPlatform		; $57
		dc.l Obj_MGZSwingingSpikeBall		; $58
		dc.l Obj_MGZDashTrigger			; $59
		dc.l Obj_MGZPulley			; $5A
		dc.l Obj_MGZTopPlatform			; $5B
		dc.l Obj_MGZTopLauncher			; $5C
		dc.l Obj_CGZTriangleBumpers		; $5D
		dc.l Obj_CGZBladePlatform		; $5E
		dc.l Obj_2PRetractingSpring		; $5F
		dc.l Obj_BPZElephantBlock		; $60
		dc.l Obj_BPZBalloon			; $61
		dc.l Obj_DPZDisolvingSandBar		; $62
		dc.l Obj_DPZButton			; $63
		dc.l Obj_2PItem				; $64
		dc.l Obj_2PGoalMarker			; $65
		dc.l Obj_EMZDripper			; $66
		dc.l Obj_HCZSnakeBlocks			; $67
		dc.l Obj_HCZSpinningColumn		; $68
		dc.l Obj_HCZTwistingLoop		; $69
		dc.l Obj_InvisibleHurtBlockHorizontal	; $6A
		dc.l Obj_InvisibleHurtBlockVertical	; $6B
		dc.l Obj_TensionBridge			; $6C
		dc.l Obj_HCZWaterSplash			; $6D
		dc.l Obj_WaterDrop			; $6E
		dc.l Obj_Ring				; $6F
		dc.l Obj_Ring				; $70
		dc.l Obj_Ring				; $71
		dc.l Obj_Ring				; $72
		dc.l Obj_Ring				; $73
		dc.l Obj_Ring				; $74
		dc.l Obj_Ring				; $75
		dc.l Obj_Ring				; $76
		dc.l Obj_Ring				; $77
		dc.l Obj_Ring				; $78
		dc.l Obj_Ring				; $79
		dc.l Obj_Ring				; $7A
		dc.l Obj_Ring				; $7B
		dc.l Obj_Ring				; $7C
		dc.l Obj_Ring				; $7D
		dc.l Obj_Ring				; $7E
		dc.l Obj_Ring				; $7F
		dc.l Obj_AIZMinibossCutscene		; $80
		dc.l Obj_Bloominator			; $81
		dc.l Obj_Rhinobot			; $82
		dc.l Obj_MonkeyDude			; $83
		dc.l Delete_Current_Sprite		; $84
		dc.l Obj_LBZMiniboss			; $85
		dc.l Obj_LBZFinalBoss1			; $86
		dc.l Obj_SnaleBlaster			; $87
		dc.l Obj_Ribot				; $88
		dc.l Obj_Orbinaut			; $89
		dc.l Obj_Corkey				; $8A
		dc.l Obj_Flybot767			; $8B
		dc.l Obj_LBZEndBoss			; $8C
		dc.l Obj_CNZEndBoss			; $8D
		dc.l Obj_CNZMiniboss			; $8E
		dc.l Obj_FBZMiniboss			; $8F
		dc.l Delete_Current_Sprite		; $90
		dc.l Delete_Current_Sprite		; $91
		dc.l Delete_Current_Sprite		; $92
		dc.l Delete_Current_Sprite		; $93
		dc.l Delete_Current_Sprite		; $94
		dc.l Delete_Current_Sprite		; $95
		dc.l Delete_Current_Sprite		; $96
		dc.l Delete_Current_Sprite		; $97
		dc.l Delete_Current_Sprite		; $98
		dc.l Obj_Jawz				; $99
		dc.l Obj_Blastoid			; $9A
		dc.l Obj_Buggernaut			; $9B
		dc.l Obj_TurboSpiker			; $9C
		dc.l Obj_MegaChopper			; $9D
		dc.l Obj_Poindexter			; $9E
		dc.l Obj_CaterKillerJr			; $9F
		dc.l Obj_Clamer				; $A0
		dc.l Obj_Sparkle			; $A1
		dc.l Obj_Batbot				; $A2
		dc.l Obj_BubblesBadnik			; $A3
		dc.l Obj_Tunnelbot			; $A4
		dc.l Obj_Spiker				; $A5
		dc.l Obj_Mantis				; $A6
		dc.l Obj_Blaster			; $A7
		dc.l Obj_TechnoSqueek			; $A8
		dc.l Obj_AIZEndBoss			; $A9
		dc.l Obj_Penguinator			; $AA
		dc.l Obj_StarPointer			; $AB
		dc.l Obj_AIZMiniboss			; $AC
		dc.l Obj_HCZMiniboss			; $AD
		dc.l Obj_LBZ1Robotnik			; $AE
		dc.l Obj_MGZ2DrillingRobotnik		; $AF
		dc.l Obj_MGZEndBoss			; $B0
		dc.l Obj_MGZEndBossKnux			; $B1
		dc.l Obj_ICZEndBoss			; $B2
		dc.l Obj_ICZMiniboss			; $B3
		dc.l Obj_FBZEndBoss			; $B4
		dc.l Obj_HCZEndBoss			; $B5
		dc.l Obj_FBZ2Subboss			; $B6
		dc.l Obj_LBZ2RobotnikShip		; $B7
		dc.l Obj_ICZCrushingColumn		; $B8
		dc.l Obj_ICZPathFollowPlatform		; $B9
		dc.l Obj_ICZBreakableWall		; $BA
		dc.l Obj_ICZFreezer			; $BB
		dc.l Obj_ICZSegmentColumn		; $BC
		dc.l Obj_ICZSwingingPlatform		; $BD
		dc.l Obj_ICZStalagtite			; $BE
		dc.l Obj_ICZIceCube			; $BF
		dc.l Obj_ICZIceSpikes			; $C0
		dc.l Obj_ICZHarmfulIce			; $C1
		dc.l Obj_ICZSnowPile			; $C2
		dc.l Obj_ICZTensionPlatform		; $C3
		dc.l Obj_MGZMiniboss			; $C4
		dc.l Obj_HiddenMonitor			; $C5
		dc.l Obj_EggCapsule			; $C6
		dc.l Obj_CutsceneKnuckles		; $C7
		dc.l Obj_ICZIceBlock			; $C8
		dc.l Obj_CutsceneButton			; $C9
		dc.l Obj_AIZPlaneIntro			; $CA
		dc.l Obj_SSEntryRing			; $CB
		dc.l Obj_LBZMinibossBox			; $CC
		dc.l Obj_LBZ2UnusedRobotnik		; $CD
		dc.l Obj_GumballMachine			; $CE
		dc.l Obj_GumballTriangleBumper		; $CF
		dc.l Obj_LBZFinalBoss2			; $D0
		dc.l Obj_CNZWaterLevelCorkFloor		; $D1
		dc.l Obj_CNZWaterLevelButton		; $D2
		dc.l Obj_LBZKnuxPillar			; $D3