		dc.l Obj_Ring				; 0
		dc.l Obj_Monitor			; 1
		dc.l Obj_PathSwap			; 2
		dc.l Obj_AIZHollowTree			; 3
		dc.l Obj_CollapsingPlatform		; 4
		dc.l Obj_AIZLRZEMZRock			; 5
		dc.l Obj_AIZRideVine			; 6
		dc.l Obj_Spring				; 7
		dc.l Obj_Spikes				; 8
		dc.l Obj_AIZ1Tree			; 9
		dc.l Obj_AIZ1ZiplinePeg			; $A
		dc.l Obj_Ring				; $B
		dc.l Obj_AIZGiantRideVine		; $C
		dc.l Obj_BreakableWall			; $D
		dc.l Obj_TwistedRamp			; $E
		dc.l Obj_CollapsingBridge		; $F
		dc.l Obj_LBZTubeElevator		; $10
		dc.l Obj_LBZMovingPlatform		; $11
		dc.l Obj_LBZUnusedElevator		; $12
		dc.l Obj_LBZExplodingTrigger		; $13
		dc.l Obj_LBZTriggerBridge		; $14
		dc.l Obj_LBZPlayerLauncher		; $15
		dc.l Obj_LBZFlameThrower		; $16
		dc.l Obj_LBZRideGrapple			; $17
		dc.l Obj_LBZCupElevator			; $18
		dc.l Obj_LBZCupElevatorPole		; $19
		dc.l Obj_LBZUnusedTiltingBridge		; $1A
		dc.l Obj_LBZPipePlug			; $1B
		dc.l Obj_Ring				; $1C
		dc.l Obj_LBZUnusedBarPlatform		; $1D
		dc.l Obj_LBZSpinLauncher		; $1E
		dc.l Obj_LBZLoweringGrapple		; $1F
		dc.l Obj_MGZLBZSmashingPillar		; $20
		dc.l Obj_LBZGateLaser			; $21
		dc.l Obj_LBZAlarm			; $22
		dc.l Obj_LBZUnusedForceFall		; $23
		dc.l Obj_AutomaticTunnel		; $24
		dc.l Obj_Ring				; $25
		dc.l Obj_AutoSpin			; $26
		dc.l Obj_S2LavaMarker			; $27
		dc.l Obj_InvisibleBlock			; $28
		dc.l Obj_AIZDisappearingFloor		; $29
		dc.l Obj_CorkFloor			; $2A
		dc.l Obj_AIZFlippingBridge		; $2B
		dc.l Obj_AIZCollapsingLogBridge		; $2C
		dc.l Obj_AIZFallingLog			; $2D
		dc.l Obj_AIZSpikedLog			; $2E
		dc.l Obj_StillSprite			; $2F
		dc.l Obj_AnimatedStillSprite		; $30
		dc.l Obj_LBZRollingDrum			; $31
		dc.l Obj_AIZDrawBridge			; $32
		dc.l Obj_Button				; $33
		dc.l Obj_StarPost			; $34
		dc.l Obj_AIZForegroundPlant		; $35
		dc.l Obj_HCZBreakableBar		; $36
		dc.l Obj_HCZWaterRush			; $37
		dc.l Obj_HCZCGZFan			; $38
		dc.l Obj_HCZLargeFan			; $39
		dc.l Obj_HCZHandLauncher		; $3A
		dc.l Obj_HCZWaterWall			; $3B
		dc.l Obj_Door				; $3C
		dc.l Obj_RetractingSpring		; $3D
		dc.l Obj_HCZConveyorBelt		; $3E
		dc.l Obj_HCZConveryorSpike		; $3F
		dc.l Obj_HCZBlock			; $40
		dc.l Obj_CNZBalloon			; $41
		dc.l Obj_CNZCannon			; $42
		dc.l Obj_CNZRisingPlatform		; $43
		dc.l Obj_CNZTrapDoor			; $44
		dc.l Obj_CNZLightBulb			; $45
		dc.l Obj_CNZHoverFan			; $46
		dc.l Obj_CNZCylinder			; $47
		dc.l Obj_CNZVacuumTube			; $48
		dc.l Obj_CNZGiantWheel			; $49
		dc.l Obj_Bumper				; $4A
		dc.l Obj_CNZTriangleBumpers		; $4B
		dc.l Obj_CNZSpiralTube			; $4C
		dc.l Obj_CNZBarberPoleSprite		; $4D
		dc.l Obj_CNZWireCage			; $4E
		dc.l Obj_SinkingMud			; $4F
		dc.l Obj_MGZTwistingLoop		; $50
		dc.l Obj_FloatingPlatform		; $51
		dc.l Obj_MGZLBZSmashingPillar		; $52
		dc.l Obj_MGZSwingingPlatform		; $53
		dc.l Obj_Bubbler			; $54
		dc.l Obj_MGZHeadTrigger			; $55
		dc.l Obj_MGZMovingSpikePlatform		; $56
		dc.l Obj_MGZTriggerPlatform		; $57
		dc.l Obj_MGZSwingingSpikeBall		; $58
		dc.l Obj_MGZDashTrigger			; $59
		dc.l Obj_MGZPulley			; $5A
		dc.l Obj_MGZTopPlatform			; $5B
		dc.l Obj_MGZTopLauncher			; $5C
		dc.l Obj_CGZTriangleBumpers		; $5D
		dc.l Obj_CGZBladePlatform		; $5E
		dc.l Obj_2PRetractingSpring		; $5F
		dc.l Obj_BPZElephantBlock		; $60
		dc.l Obj_BPZBalloon			; $61
		dc.l Obj_DPZDisolvingSandBar		; $62
		dc.l Obj_DPZButton			; $63
		dc.l Obj_2PItem				; $64
		dc.l Obj_2PGoalMarker			; $65
		dc.l Obj_EMZDripper			; $66
		dc.l Obj_HCZSnakeBlocks			; $67
		dc.l Obj_HCZSpinningColumn		; $68
		dc.l Obj_HCZTwistingLoop		; $69
		dc.l Obj_InvisibleHurtBlockHorizontal	; $6A
		dc.l Obj_InvisibleHurtBlockVertical	; $6B
		dc.l Obj_TensionBridge			; $6C
		dc.l Obj_HCZWaterSplash			; $6D
		dc.l Obj_WaterDrop			; $6E
		dc.l Obj_FBZWireCage			; $6F
		dc.l Obj_FBZWireCageStationary		; $70
		dc.l Obj_FBZFloatingPlatform		; $71
		dc.l Obj_FBZChainLink			; $72
		dc.l Obj_FBZMagneticSpikeBall		; $73
		dc.l Obj_FBZMagneticPlatform		; $74
		dc.l Obj_FBZSnakePlatform		; $75
		dc.l Obj_FBZBentPipe			; $76
		dc.l Obj_FBZRotatingPlatform		; $77
		dc.l Obj_FBZDEZPlayerLauncher		; $78
		dc.l Obj_FBZDisappearingPlatform	; $79
		dc.l Obj_FBZScrewDoor			; $7A
		dc.l Obj_FBZSpinningPole		; $7B
		dc.l Obj_FBZPropeller			; $7C
		dc.l Obj_FBZPiston			; $7D
		dc.l Obj_FBZPlatformBlocks		; $7E
		dc.l Obj_FBZMissileLauncher		; $7F
		dc.l Obj_HiddenMonitor			; $80
		dc.l Obj_EggCapsule			; $81
		dc.l Obj_CutsceneKnuckles		; $82
		dc.l Obj_CutsceneButton			; $83
		dc.l Obj_AIZPlaneIntro			; $84
		dc.l Obj_SSEntryRing			; $85
		dc.l Obj_GumballMachine			; $86
		dc.l Obj_GumballTriangleBumper		; $87
		dc.l Obj_CNZWaterLevelCorkFloor		; $88
		dc.l Obj_CNZWaterLevelButton		; $89
		dc.l Obj_FBZExitHall			; $8A
		dc.l Obj_SpriteMask			; $8B
		dc.l Obj_Bloominator			; $8C
		dc.l Obj_Rhinobot			; $8D
		dc.l Obj_MonkeyDude			; $8E
		dc.l Obj_CaterKillerJr			; $8F
		dc.l Obj_AIZMinibossCutscene		; $90
		dc.l Obj_AIZMiniboss			; $91
		dc.l Obj_AIZEndBoss			; $92
		dc.l Obj_Jawz				; $93
		dc.l Obj_Blastoid			; $94
		dc.l Obj_Buggernaut			; $95
		dc.l Obj_TurboSpiker			; $96
		dc.l Obj_MegaChopper			; $97
		dc.l Obj_Poindexter			; $98
		dc.l Obj_HCZMiniboss			; $99
		dc.l Obj_HCZEndBoss			; $9A
		dc.l Obj_BubblesBadnik			; $9B
		dc.l Obj_Spiker				; $9C
		dc.l Obj_Mantis				; $9D
		dc.l Obj_Tunnelbot			; $9E
		dc.l Obj_MGZMiniboss			; $9F
		dc.l Obj_MGZ2DrillingRobotnik		; $A0
		dc.l Obj_MGZEndBoss			; $A1
		dc.l Obj_MGZEndBossKnux			; $A2
		dc.l Obj_Clamer				; $A3
		dc.l Obj_Sparkle			; $A4
		dc.l Obj_Batbot				; $A5
		dc.l Obj_CNZMiniboss			; $A6
		dc.l Obj_CNZEndBoss			; $A7
		dc.l Obj_Blaster			; $A8
		dc.l Obj_TechnoSqueek			; $A9
		dc.l Obj_FBZMiniboss			; $AA
		dc.l Obj_FBZ2Subboss			; $AB
		dc.l Obj_FBZEndBoss			; $AC
		dc.l Obj_Penguinator			; $AD
		dc.l Obj_StarPointer			; $AE
		dc.l Obj_ICZCrushingColumn		; $AF
		dc.l Obj_ICZPathFollowPlatform		; $B0
		dc.l Obj_ICZBreakableWall		; $B1
		dc.l Obj_ICZFreezer			; $B2
		dc.l Obj_ICZSegmentColumn		; $B3
		dc.l Obj_ICZSwingingPlatform		; $B4
		dc.l Obj_ICZStalagtite			; $B5
		dc.l Obj_ICZIceCube			; $B6
		dc.l Obj_ICZIceSpikes			; $B7
		dc.l Obj_ICZHarmfulIce			; $B8
		dc.l Obj_ICZSnowPile			; $B9
		dc.l Obj_ICZTensionPlatform		; $BA
		dc.l Obj_ICZIceBlock			; $BB
		dc.l Obj_ICZMiniboss			; $BC
		dc.l Obj_ICZEndBoss			; $BD
		dc.l Obj_SnaleBlaster			; $BE
		dc.l Obj_Ribot				; $BF
		dc.l Obj_Orbinaut			; $C0
		dc.l Obj_Corkey				; $C1
		dc.l Obj_Flybot767			; $C2
		dc.l Obj_LBZ1Robotnik			; $C3
		dc.l Obj_LBZMinibossBox			; $C4
		dc.l Obj_LBZMinibossBoxKnux		; $C5
		dc.l Obj_LBZ2RobotnikShip		; $C6
		dc.l Obj_Ring				; $C7
		dc.l Obj_LBZKnuxPillar			; $C8
		dc.l Obj_LBZMiniboss			; $C9
		dc.l Obj_LBZFinalBoss1			; $CA
		dc.l Obj_LBZEndBoss			; $CB
		dc.l Obj_LBZFinalBoss2			; $CC
		dc.l Obj_LBZFinalBossKnux		; $CD
		dc.l Obj_FBZExitDoor			; $CE
		dc.l Obj_FBZEggPrison			; $CF
		dc.l Obj_FBZSpringPlunger		; $D0
		dc.l Obj_Ring				; $D1
		dc.l Obj_Ring				; $D2
		dc.l Obj_Ring				; $D3
		dc.l Obj_Ring				; $D4
		dc.l Obj_Ring				; $D5
		dc.l Obj_Ring				; $D6
		dc.l Obj_Ring				; $D7
		dc.l Obj_Ring				; $D8
		dc.l Obj_Ring				; $D9
		dc.l Obj_Ring				; $DA
		dc.l Obj_Ring				; $DB
		dc.l Obj_Ring				; $DC
		dc.l Obj_Ring				; $DD
		dc.l Obj_Ring				; $DE
		dc.l Obj_Ring				; $DF
		dc.l Obj_FBZWallMissile			; $E0
		dc.l Obj_FBZMine			; $E1
		dc.l Obj_FBZElevator			; $E2
		dc.l Obj_FBZTrapSpring			; $E3
		dc.l Obj_FBZFlamethrower		; $E4
		dc.l Obj_FBZSpiderCrane			; $E5
		dc.l Obj_PachinkoTriangleBumper		; $E6
		dc.l Obj_PachinkoFlipper		; $E7
		dc.l Obj_PachinkoEnergyTrap		; $E8
		dc.l Obj_PachinkoInvisibleUnknown	; $E9
		dc.l Obj_Pachinko_Platform		; $EA
		dc.l Obj_GumballItem			; $EB
		dc.l Obj_PachinkoMagnetOrb		; $EC
		dc.l Obj_PachinkoItemOrb		; $ED
		dc.l Obj_Ring				; $EE
		dc.l Obj_Ring				; $EF
		dc.l Obj_Ring				; $F0
		dc.l Obj_Ring				; $F1
		dc.l Obj_Ring				; $F2
		dc.l Obj_Ring				; $F3
		dc.l Obj_Ring				; $F4
		dc.l Obj_Ring				; $F5
		dc.l Obj_Ring				; $F6
		dc.l Obj_Ring				; $F7
		dc.l Obj_Ring				; $F8
		dc.l Obj_Ring				; $F9
		dc.l Obj_Ring				; $FA
		dc.l Obj_Ring				; $FB
		dc.l Obj_Ring				; $FC
		dc.l Obj_Ring				; $FD
		dc.l Obj_Ring				; $FE
		dc.l Obj_FBZMagneticPendulum		; $FF